/* mpfrg.vapi generated by valac 0.44.3, do not modify. */

namespace MPFRG {
	[CCode (cheader_filename = "mpfrg.h")]
	[Compact]
	public class RealRef {
		public MPFR.Real val;
		public RealRef ();
	}
}
